const Productterm =[
  {
    id: 1,
    Title: "Casual Trouser 1",
    img: require("../menasset/trouser.jpg"),
    des: "Dress Code: Casual. Perfect for everyday wear. Price: $29.99",
    price: "$29.99",
    category: "trouser",
  },
  {
    id: 2,
    Title: "Smart Trouser 2",
    img: require("../menasset/trouser1.jpg"),
    des: "Dress Code: Smart casual. Ideal for both work and play. Price: $32.49",
    price: "$32.49",
    category: "trouser",
  },
  {
    id: 3,
    Title: "Comfort Trouser 3",
    img: require("../menasset/trouser2.jpg"),
    des: "Dress Code: Comfortable. Great for relaxing. Price: $27.99",
    price: "$27.99",
    category: "trouser",
  },
  {
    id: 4,
    Title: "Relaxed Trouser 4",
    img: require("../menasset/trouser3.jpg"),
    des: "Dress Code: Relaxed. Ideal for casual outings. Price: $28.99",
    price: "$28.99",
    category: "trouser",
  },
  {
    id: 5,
    Title: "Daily Trouser 5",
    img: require("../menasset/trouser.jpg"),
    des: "Dress Code: Daily wear. Perfect for a laid-back look. Price: $30.49",
    price: "$30.49",
    category: "trouser",
  },
  {
    id: 6,
    Title: "Stylish Trouser 6",
    img: require("../menasset/trouser5.jpg"),
    des: "Dress Code: Stylish. Great for a trendy appearance. Price: $33.99",
    price: "$33.99",
    category: "trouser",
  },
  {
    id: 7,
    Title: "Classic Trouser 7",
    img: require("../menasset/trouser6.jpg"),
    des: "Dress Code: Classic. Ideal for versatile outfits. Price: $31.49",
    price: "$31.49",
    category: "trouser",
  },
  {
    id: 8,
    Title: "Cargo Trouser 8",
    img: require("../menasset/cargo10.jpg"),
    des: "Dress Code: Casual and functional. Perfect for outdoor activities. Price: $34.99",
    price: "$34.99",
    category: "trouser",
  },
  {
    id: 9,
    Title: "Utility Cargo 9",
    img: require("../menasset/cargo1.jpg"),
    des: "Dress Code: Utility. Ideal for practical wear. Price: $35.49",
    price: "$35.49",
    category: "trouser",
  },
  {
    id: 10,
    Title: "Comfort Cargo 10",
    img: require("../menasset/cargo2.jpg"),
    des: "Dress Code: Comfortable. Great for a relaxed style. Price: $36.99",
    price: "$36.99",
    category: "trouser",
  },
  {
    id: 11,
    Title: "Urban Cargo 11",
    img: require("../menasset/cargo3.jpg"),
    des: "Dress Code: Urban. Ideal for a modern look. Price: $37.49",
    price: "$37.49",
    category: "trouser",
  },
  {
    id: 12,
    Title: "Tactical Cargo 12",
    img: require("../menasset/cargo4.jpg"),
    des: "Dress Code: Tactical. Perfect for rugged use. Price: $38.99",
    price: "$38.99",
    category: "trouser",
  },
  {
    id: 13,
    Title: "Outdoor Cargo 13",
    img: require("../menasset/cargo5.jpg"),
    des: "Dress Code: Outdoor. Ideal for adventures. Price: $39.49",
    price: "$39.49",
    category: "trouser",
  },
  {
    id: 14,
    Title: "Adventure Cargo 14",
    img: require("../menasset/cargo6.jpg"),
    des: "Dress Code: Adventure. Great for active lifestyles. Price: $40.99",
    price: "$40.99",
    category: "trouser",
  },
  {
    id: 15,
    Title: "Fashion Cargo 15",
    img: require("../menasset/cargo8.jpg"),
    des: "Dress Code: Fashionable. Perfect for a trendy look. Price: $41.49",
    price: "$41.49",
    category: "trouser",
  },
  {
    id: 16,
    Title: "Chic Cargo 16",
    img: require("../menasset/cargo9.jpg"),
    des: "Dress Code: Chic. Ideal for stylish appearances. Price: $42.99",
    price: "$42.99",
    category: "trouser",
  },
  {
    id: 17,
    Title: "Modern Trouser 17",
    img: require("../menasset/trouser12.jpg"),
    des: "Dress Code: Modern. Great for contemporary looks. Price: $31.99",
    price: "$31.99",
    category: "trouser",
  },
  {
    id: 18,
    Title: "Trendy Trouser 18",
    img: require("../menasset/trouser8.jpg"),
    des: "Dress Code: Trendy. Ideal for a fashionable style. Price: $32.99",
    price: "$32.99",
    category: "trouser",
  },
  {
    id: 19,
    Title: "Elegant Trouser 19",
    img: require("../menasset/trouser9.jpg"),
    des: "Dress Code: Elegant. Perfect for dressier occasions. Price: $34.49",
    price: "$34.49",
    category: "trouser",
  },
  {
    id: 20,
    Title: "Casual Trouser 20",
    img: require("../menasset/trouser10.jpg"),
    des: "Dress Code: Casual. Great for everyday wear. Price: $29.49",
    price: "$29.49",
    category: "trouser",
  },
  {
    id: 21,
    Title: "Relaxed Trouser 21",
    img: require("../menasset/trouser11.jpg"),
    des: "Dress Code: Relaxed. Ideal for a laid-back style. Price: $30.99",
    price: "$30.99",
    category: "trouser",
  },
  {
    id: 22,
    Title: "Smart Trouser 22",
    img: require("../menasset/trouser14.jpg"),
    des: "Dress Code: Smart. Perfect for versatile outfits. Price: $32.49",
    price: "$32.49",
    category: "trouser",
  },
  {
    id: 23,
    Title: "Utility Cargo 23",
    img: require("../menasset/cargo10.jpg"),
    des: "Dress Code: Utility. Ideal for practical wear. Price: $33.99",
    price: "$33.99",
    category: "trouser",
  },
  {
    id: 24,
    Title: "Comfort Cargo 24",
    img: require("../menasset/cargo11.jpg"),
    des: "Dress Code: Comfortable. Great for a relaxed style. Price: $35.49",
    price: "$35.49",
    category: "trouser",
  },
  {
    id: 25,
    Title: "Adventure Cargo 25",
    img: require("../menasset/trouser15.jpg"),
    des: "Dress Code: Adventure. Ideal for outdoor activities. Price: $36.99",
    price: "$36.99",
    category: "trouser",
  },
  {
    id: 26,
    Title: "Chic Trouser 26",
    img: require("../menasset/trouser16.jpg"),
    des: "Dress Code: Chic. Perfect for stylish appearances. Price: $37.49",
    price: "$37.49",
    category: "trouser",
  },
  {
    id: 27,
    Title: "Fashion Trouser 27",
    img: require("../menasset/trouser17.jpg"),
    des: "Dress Code: Fashionable. Great for modern looks. Price: $38.49",
    price: "$38.49",
    category: "trouser",
  },
  {
    id: 28,
    Title: "Urban Trouser 28",
    img: require("../menasset/trouser8.jpg"),
    des: "Dress Code: Urban. Ideal for city life. Price: $29.99",
    price: "$29.99",
    category: "trouser",
  },
  {
    id: 29,
    Title: "Modern Trouser 29",
    img: require("../menasset/trouser19.jpg"),
    des: "Dress Code: Modern. Perfect for a sleek style. Price: $32.99",
    price: "$32.99",
    category: "trouser",
  },
  {
    id: 30,
    Title: "Elegant Trouser 30",
    img: require("../menasset/trouser20.jpg"),
    des: "Dress Code: Elegant. Ideal for dressier occasions. Price: $33.49",
    price: "$33.49",
    category: "trouser",
  },
  {
    id: 31,
    Title: "Versatile Trouser 31",
    img: require("../menasset/trouser30.jpg"),
    des: "Dress Code: Versatile. Great for any event. Price: $34.99",
    price: "$34.99",
    category: "trouser",
  },
  {
    id: 32,
    Title: "Smart Trouser 32",
    img: require("../menasset/trouser11.jpg"),
    des: "Dress Code: Smart. Ideal for professional settings. Price: $35.49",
    price: "$35.49",
    category: "trouser",
  },
  {
    id: 33,
    Title: "Unisex Clothing 1",
    img: require("../menasset/clothing.jpg"),
    des: "Dress Code: Unisex. Perfect for all genders. Price: $40.99",
    price: "$40.99",
    category: "unisex",
  },
  {
    id: 34,
    Title: "Unisex Clothing 2",
    img: require("../menasset/clothing1.jpg"),
    des: "Dress Code: Unisex. Great for everyday wear. Price: $41.49",
    price: "$41.49",
    category: "unisex",
  },
  {
    id: 35,
    Title: "Unisex Clothing 3",
    img: require("../menasset/clothing2.jpg"),
    des: "Dress Code: Unisex. Ideal for casual outfits. Price: $42.99",
    price: "$42.99",
    category: "unisex",
  },
  {
    id: 36,
    Title: "Unisex Clothing 4",
    img: require("../menasset/clothing3.jpg"),
    des: "Dress Code: Unisex. Perfect for versatile wear. Price: $43.49",
    price: "$43.49",
    category: "unisex",
  },
  {
    id: 37,
    Title: "Unisex Clothing 5",
    img: require("../menasset/clothing4.jpg"),
    des: "Dress Code: Unisex. Ideal for any occasion. Price: $44.99",
    price: "$44.99",
    category: "unisex",
  },
  {
    id: 38,
    Title: "Extra Clothing 6",
    img: require("../menasset/extra.jpg"),
    des: "Dress Code: Unisex. Great for extra comfort. Price: $45.49",
    price: "$45.49",
    category: "unisex",
  },
  {
    id: 39,
    Title: "Unisex Clothing 7",
    img: require("../menasset/clothing5.jpg"),
    des: "Dress Code: Unisex. Ideal for everyday outfits. Price: $46.99",
    price: "$46.99",
    category: "unisex",
  },
  {
    id: 40,
    Title: "Unisex Clothing 8",
    img: require("../menasset/clothing6.jpg"),
    des: "Dress Code: Unisex. Perfect for all occasions. Price: $47.49",
    price: "$47.49",
    category: "unisex",
  },
  {
    id: 41,
    Title: "Unisex Clothing 9",
    img: require("../menasset/clothing7.jpg"),
    des: "Dress Code: Unisex. Great for a casual look. Price: $48.99",
    price: "$48.99",
    category: "unisex",
  },
  {
    id: 42,
    Title: "Unisex Clothing 10",
    img: require("../menasset/clothing8.jpg"),
    des: "Dress Code: Unisex. Ideal for stylish wear. Price: $49.49",
    price: "$49.49",
    category: "unisex",
  },
  {
    id: 43,
    Title: "Unisex Clothing 11",
    img: require("../menasset/clothing9.jpg"),
    des: "Dress Code: Unisex. Perfect for versatile styles. Price: $50.99",
    price: "$50.99",
    category: "unisex",
  },
  {
    id: 44,
    Title: "Unisex Clothing 12",
    img: require("../menasset/clothing10.jpg"),
    des: "Dress Code: Unisex. Ideal for any occasion. Price: $51.49",
    price: "$51.49",
    category: "unisex",
  },
  {
    id: 45,
    Title: "Unisex Clothing 13",
    img: require("../menasset/clothing11.jpg"),
    des: "Dress Code: Unisex. Great for all-day wear. Price: $52.99",
    price: "$52.99",
    category: "unisex",
  },
  {
    id: 46,
    Title: "Unisex Clothing 14",
    img: require("../menasset/clothing12.jpg"),
    des: "Dress Code: Unisex. Perfect for comfortable style. Price: $53.49",
    price: "$53.49",
    category: "unisex",
  },
  {
    id: 47,
    Title: "Unisex Clothing 15",
    img: require("../menasset/clothing13.jpg"),
    des: "Dress Code: Unisex. Ideal for relaxed wear. Price: $54.99",
    price: "$54.99",
    category: "unisex",
  },
  {
    id: 48,
    Title: "Unisex Clothing 16",
    img: require("../menasset/clothing15.jpg"),
    des: "Dress Code: Unisex. Great for casual outfits. Price: $51.49",
    price: "$51.49",
    category: "unisex",
  },
  {
    id: 49,
    Title: "Unisex Clothing 17",
    img: require("../menasset/clothing16.jpg"),
    des: "Dress Code: Unisex. Perfect for all-day comfort. Price: $56.99",
    price: "$46.99",
    category: "unisex",
  },
  {
    id: 50,
    Title: "Unisex Clothing 18",
    img: require("../menasset/clothing17.jpg"),
    des: "Dress Code: Unisex. Ideal for versatile style. Price: $57.49",
    price: "$57.49",
    category: "unisex",
  },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing19.jpg"),
        des: "Dress Code: Stylish shorts ideal for casual wear. Affordable and trendy.",
       price: "$22.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing21.jpg"),
        des: "Dress Code: Comfortable shorts perfect for relaxed wear. Stylish and budget-friendly.",
          price: "$19.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing22.jpg"),
        des: "Dress Code: Trendy shorts with a modern design. Great fashion at an affordable price.",
         price: "$20.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing23.jpg"),
        des: "Dress Code: Bright shorts ideal for a vibrant summer appearance. Affordable and stylish.",
       price: "$18.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing24.jpg"),
         des: "Dress Code: Comfortable and practical. Perfect for an active lifestyle. Price: $20.99",
        price: "$20.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing25.jpg"),
        des: "Dress Code: Chic and stylish. Ideal for both casual and semi-formal events. Price: $21.99",
        price: "$25.00",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing26.jpg"),
        des: "Dress Code: Comfortable and practical. Perfect for an active lifestyle. Price: $20.99",
        price: "$20.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing27.jpg"),
        des: "Dress Code: Elegant and refined. Ideal for dressier occasions. Price: $24.99",
        price: "$24.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing30.jpg"),
        des: "Dress Code: Chic and stylish. Ideal for both casual and semi-formal events. Price: $21.99",
        price: "$21.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/clothing29.jpg"),
        des: "Dress Code: Chic black trainers that enhance your style. Affordable and versatile.",
        price: "$54.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/style1.jpg"),
        des: "Dress Code: Casual and comfortable. Perfect for summer outings. Price: $19.99",
        price: "$19.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/style2.jpg"),
        des: "Dress Code: Stylish shorts for a fashionable summer appearance. Affordable and trendy.",
        price: "$22.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/style3.jpg"),
        des: "Dress Code: Bright shorts perfect for a vibrant look. Great style and value.",
      price: "$37.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/style4.jpg"),
        des: "Dress Code: Bright shorts for a lively summer wardrobe. Affordable and stylish.",
        price: "$15.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/style5.jpg"),
        des: "Dress Code: Comfortable shorts for everyday casual wear. Great value for money.",
      price: "$19.99",
        category: "unisex",
      },
      {
        id: 1,
        Title: " ",
        img: require("../menasset/style6.jpg"),
         des: "Dress Code: Elegant shorts for a refined summer look. Great value and style.",
      price: "$22.00",
        category: "unisex",
      },
      
      
      {
        id: 1,
        Title: " ",
        img: require("../menasset/style.jpg"),
        des: "Dress Code: Comfortable shorts perfect for a laid-back look. Great value and style.",
        price: "$19.00",
        category: "unisex",
      },
    












    ]
export default Productterm